// flow-typed signature: 0d0c58f70f47b8eea7b1808bdfc025b5
// flow-typed version: <<STUB>>/yr.no-forecast_v^2.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yr.no-forecast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yr.no-forecast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'yr.no-forecast/index' {
  declare module.exports: $Exports<'yr.no-forecast'>;
}
declare module 'yr.no-forecast/index.js' {
  declare module.exports: $Exports<'yr.no-forecast'>;
}
